version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      frontend:
        patterns:
          - "*"
    ignore:
      - dependency-name: "@qomicex/plugin-ui"
        update-types: [ "version-update:semver-major", "version-update:semver-minor", "version-update:semver-patch" ]

  - package-ecosystem: cargo
    directory: /src-backend/qomicex-backend
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    groups:
      backend:
        patterns:
          - "*"
