packages:
  - 'packages/*'
allowBuilds:
  esbuild: false
minimumReleaseAgeExclude:
  - '@qomicex/plugin-ui@0.1.0'
onlyBuiltDependencies: '["esbuild"]'
overrides:
  '@qomicex/cli': link:packages/qomicex-cli
