import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import type { IconDefinition } from '@fortawesome/fontawesome-svg-core'

import {
  faHouse, faCube, faDownload, faUpload, faUser, faUserPlus, faUserMinus, faUserXmark,
  faGear, faCompass, faGamepad, faNetworkWired, faWifi, faServer, faDatabase,
  faSearch, faMagnifyingGlass, faTrashCan, faPen, faPenToSquare, faSave, faCopy,
  faPlay, faPause, faStop, faSpinner, faCircleNotch,
  faCheck, faCircleCheck, faXmark, faCircleXmark, faPlus, faMinus, faCirclePlus, faCircleMinus,
  faCircleQuestion, faTriangleExclamation, faCircleExclamation, faCircleInfo,
  faStar, faHeart, faThumbsUp, faThumbsDown, faComment, faComments, faEnvelope,
  faPaperPlane, faLink, faShare, faCode, faTerminal,
  faBolt, faLightbulb, faFire, faFlask, faAtom, faMicroscope, faDna, faBrain,
  faRobot, faMicrochip, faMemory, faHardDrive,
  faShield, faShieldHalved, faLock, faUnlock, faKey, faFingerprint,
  faGlobe, faLanguage, faMap, faMapMarkerAlt, faMapPin, faLocationDot,
  faRocket, faPlane, faCar, faBus, faTrain, faShip, faBicycle,
  faSun, faMoon, faCloud, faCloudSun, faCloudRain, faSnowflake, faUmbrella,
  faWrench, faTools, faToolbox, faScrewdriver, faHammer,
  faPaintbrush, faPalette, faMagic, faWandMagicSparkles,
  faMusic, faImage, faVideo, faCamera, faMicrophone, faHeadphones,
  faBell, faFlag, faBookmark, faTag, faTags,
  faStore,
  faFolder, faFolderOpen, faFolderPlus, faFolderMinus, faFile, faFileLines, faFileCode,
  faBox, faLayerGroup, faProjectDiagram, faSitemap,
  faChartBar, faChartLine, faChartPie,
  faCalendar, faClock, faHistory, faHourglass, faStopwatch,
  faBatteryFull, faBatteryHalf, faBatteryEmpty,
  faPlug, faPowerOff, faToggleOn, faToggleOff,
  faSquare, faSquareCheck, faCircle, faCircleDot,
  faFilter, faSort, faSortUp, faSortDown,
  faArrowUp, faArrowDown, faArrowLeft, faArrowRight,
  faChevronUp, faChevronDown, faChevronLeft, faChevronRight,
  faAngleUp, faAngleDown, faAngleLeft, faAngleRight,
  faRightLeft, faRotateLeft, faRotateRight,
  faClipboard, faClipboardCheck, faClipboardList,
  faList, faListUl, faListOl, faListCheck,
  faTable, faTableCells, faTableList, faTableColumns,
  faAlignLeft, faAlignCenter, faAlignRight, faAlignJustify,
  faBold, faItalic, faUnderline, faStrikethrough,
  faQuoteLeft, faQuoteRight,
  faEye, faEyeSlash,
  faExpand, faCompress, faVolumeUp, faVolumeDown, faVolumeMute,
  faBackward, faForward, faStepBackward, faStepForward,
  faLongArrowUp, faLongArrowDown, faLongArrowAltLeft, faLongArrowAltRight,
  faUpRightAndDownLeftFromCenter, faDownLeftAndUpRightToCenter,
  faExternalLinkAlt,
  faUsers, faPeopleCarry, faUserGroup, faUsersCog, faUsersGear,
  faUserLarge, faUserCircle, faUserAlt, faUserDoctor, faUserTie,
  faUserShield, faUserLock, faUserSecret, faUserAstronaut, faUserNinja, faUserCheck, faUserGear,
  faChild, faPerson, faPersonWalking, faPersonRunning, faPersonBiking,
} from '@fortawesome/free-solid-svg-icons'
import {
  faGithub, faGitlab, faBitbucket, faDiscord, faTelegram,
  faTwitter, faXTwitter, faYoutube, faTwitch, faReddit,
  faSteam, faXbox, faPlaystation,
  faLinux, faWindows, faApple, faAndroid, faChrome, faFirefox, faSafari, faEdge,
  faPython, faJs, faHtml5, faCss3Alt, faReact, faVuejs, faAngular, faNodeJs,
  faGit, faGitAlt, faDocker, faAws, faMicrosoft,
  faCcVisa, faCcMastercard, faCcPaypal, faCcStripe, faCcAmex, 
  faBitcoin, faEthereum,
  faTiktok, faInstagram, faFacebook, faWeixin, faZhihu, faQq,
  faUbuntu, faDebian, faArchLinux, faJava, faPhp, faRust, faSwift,
} from '@fortawesome/free-brands-svg-icons'

const entries: { cls: string; icon: IconDefinition }[] = [
  { cls: 'fa-solid fa-house', icon: faHouse },
  { cls: 'fa-solid fa-home', icon: faHouse },
  { cls: 'fa-solid fa-cube', icon: faCube },
  { cls: 'fa-solid fa-box', icon: faBox },
  { cls: 'fa-solid fa-download', icon: faDownload },
  { cls: 'fa-solid fa-upload', icon: faUpload },
  { cls: 'fa-solid fa-user', icon: faUser },
  { cls: 'fa-solid fa-user-plus', icon: faUserPlus },
  { cls: 'fa-solid fa-user-minus', icon: faUserMinus },
  { cls: 'fa-solid fa-user-xmark', icon: faUserXmark },
  { cls: 'fa-solid fa-user-check', icon: faUserCheck },
  { cls: 'fa-solid fa-user-gear', icon: faUserGear },
  { cls: 'fa-solid fa-user-shield', icon: faUserShield },
  { cls: 'fa-solid fa-user-lock', icon: faUserLock },
  { cls: 'fa-solid fa-user-secret', icon: faUserSecret },
  { cls: 'fa-solid fa-user-astronaut', icon: faUserAstronaut },
  { cls: 'fa-solid fa-user-ninja', icon: faUserNinja },
  { cls: 'fa-solid fa-user-doctor', icon: faUserDoctor },
  { cls: 'fa-solid fa-user-tie', icon: faUserTie },
  { cls: 'fa-solid fa-user-circle', icon: faUserCircle },
  { cls: 'fa-solid fa-user-alt', icon: faUserAlt },
  { cls: 'fa-solid fa-user-large', icon: faUserLarge },
  { cls: 'fa-solid fa-users', icon: faUsers },
  { cls: 'fa-solid fa-users-cog', icon: faUsersCog },
  { cls: 'fa-solid fa-users-gear', icon: faUsersGear },
  { cls: 'fa-solid fa-user-group', icon: faUserGroup },
  { cls: 'fa-solid fa-people-carry', icon: faPeopleCarry },
  { cls: 'fa-solid fa-child', icon: faChild },
  { cls: 'fa-solid fa-person', icon: faPerson },
  { cls: 'fa-solid fa-person-walking', icon: faPersonWalking },
  { cls: 'fa-solid fa-person-running', icon: faPersonRunning },
  { cls: 'fa-solid fa-person-biking', icon: faPersonBiking },
  { cls: 'fa-solid fa-gear', icon: faGear },
  { cls: 'fa-solid fa-compass', icon: faCompass },
  { cls: 'fa-solid fa-gamepad', icon: faGamepad },
  { cls: 'fa-solid fa-network-wired', icon: faNetworkWired },
  { cls: 'fa-solid fa-wifi', icon: faWifi },
  { cls: 'fa-solid fa-server', icon: faServer },
  { cls: 'fa-solid fa-database', icon: faDatabase },
  { cls: 'fa-solid fa-search', icon: faSearch },
  { cls: 'fa-solid fa-magnifying-glass', icon: faMagnifyingGlass },
  { cls: 'fa-solid fa-trash', icon: faTrashCan },
  { cls: 'fa-solid fa-trash-can', icon: faTrashCan },
  { cls: 'fa-solid fa-pen', icon: faPen },
  { cls: 'fa-solid fa-pen-to-square', icon: faPenToSquare },
  { cls: 'fa-solid fa-save', icon: faSave },
  { cls: 'fa-solid fa-copy', icon: faCopy },
  { cls: 'fa-solid fa-play', icon: faPlay },
  { cls: 'fa-solid fa-pause', icon: faPause },
  { cls: 'fa-solid fa-stop', icon: faStop },
  { cls: 'fa-solid fa-spinner', icon: faSpinner },
  { cls: 'fa-solid fa-circle-notch', icon: faCircleNotch },
  { cls: 'fa-solid fa-check', icon: faCheck },
  { cls: 'fa-solid fa-check-circle', icon: faCircleCheck },
  { cls: 'fa-solid fa-circle-check', icon: faCircleCheck },
  { cls: 'fa-solid fa-times', icon: faXmark },
  { cls: 'fa-solid fa-xmark', icon: faXmark },
  { cls: 'fa-solid fa-times-circle', icon: faCircleXmark },
  { cls: 'fa-solid fa-circle-xmark', icon: faCircleXmark },
  { cls: 'fa-solid fa-plus', icon: faPlus },
  { cls: 'fa-solid fa-minus', icon: faMinus },
  { cls: 'fa-solid fa-plus-circle', icon: faCirclePlus },
  { cls: 'fa-solid fa-circle-plus', icon: faCirclePlus },
  { cls: 'fa-solid fa-minus-circle', icon: faCircleMinus },
  { cls: 'fa-solid fa-circle-minus', icon: faCircleMinus },
  { cls: 'fa-solid fa-question-circle', icon: faCircleQuestion },
  { cls: 'fa-solid fa-circle-question', icon: faCircleQuestion },
  { cls: 'fa-solid fa-exclamation-triangle', icon: faTriangleExclamation },
  { cls: 'fa-solid fa-triangle-exclamation', icon: faTriangleExclamation },
  { cls: 'fa-solid fa-exclamation-circle', icon: faCircleExclamation },
  { cls: 'fa-solid fa-circle-exclamation', icon: faCircleExclamation },
  { cls: 'fa-solid fa-info-circle', icon: faCircleInfo },
  { cls: 'fa-solid fa-star', icon: faStar },
  { cls: 'fa-solid fa-heart', icon: faHeart },
  { cls: 'fa-solid fa-thumbs-up', icon: faThumbsUp },
  { cls: 'fa-solid fa-thumbs-down', icon: faThumbsDown },
  { cls: 'fa-solid fa-comment', icon: faComment },
  { cls: 'fa-solid fa-comments', icon: faComments },
  { cls: 'fa-solid fa-envelope', icon: faEnvelope },
  { cls: 'fa-solid fa-paper-plane', icon: faPaperPlane },
  { cls: 'fa-solid fa-link', icon: faLink },
  { cls: 'fa-solid fa-external-link-alt', icon: faExternalLinkAlt },
  { cls: 'fa-solid fa-share', icon: faShare },
  { cls: 'fa-solid fa-code', icon: faCode },
  { cls: 'fa-solid fa-terminal', icon: faTerminal },
  { cls: 'fa-solid fa-bolt', icon: faBolt },
  { cls: 'fa-solid fa-lightbulb', icon: faLightbulb },
  { cls: 'fa-solid fa-fire', icon: faFire },
  { cls: 'fa-solid fa-flask', icon: faFlask },
  { cls: 'fa-solid fa-atom', icon: faAtom },
  { cls: 'fa-solid fa-microscope', icon: faMicroscope },
  { cls: 'fa-solid fa-dna', icon: faDna },
  { cls: 'fa-solid fa-brain', icon: faBrain },
  { cls: 'fa-solid fa-robot', icon: faRobot },
  { cls: 'fa-solid fa-microchip', icon: faMicrochip },
  { cls: 'fa-solid fa-memory', icon: faMemory },
  { cls: 'fa-solid fa-hard-drive', icon: faHardDrive },
  { cls: 'fa-solid fa-shield', icon: faShield },
  { cls: 'fa-solid fa-shield-halved', icon: faShieldHalved },
  { cls: 'fa-solid fa-lock', icon: faLock },
  { cls: 'fa-solid fa-unlock', icon: faUnlock },
  { cls: 'fa-solid fa-key', icon: faKey },
  { cls: 'fa-solid fa-fingerprint', icon: faFingerprint },
  { cls: 'fa-solid fa-globe', icon: faGlobe },
  { cls: 'fa-solid fa-language', icon: faLanguage },
  { cls: 'fa-solid fa-map', icon: faMap },
  { cls: 'fa-solid fa-map-marker-alt', icon: faMapMarkerAlt },
  { cls: 'fa-solid fa-map-pin', icon: faMapPin },
  { cls: 'fa-solid fa-location-dot', icon: faLocationDot },
  { cls: 'fa-solid fa-rocket', icon: faRocket },
  { cls: 'fa-solid fa-plane', icon: faPlane },
  { cls: 'fa-solid fa-car', icon: faCar },
  { cls: 'fa-solid fa-bus', icon: faBus },
  { cls: 'fa-solid fa-train', icon: faTrain },
  { cls: 'fa-solid fa-ship', icon: faShip },
  { cls: 'fa-solid fa-bicycle', icon: faBicycle },
  { cls: 'fa-solid fa-sun', icon: faSun },
  { cls: 'fa-solid fa-moon', icon: faMoon },
  { cls: 'fa-solid fa-cloud', icon: faCloud },
  { cls: 'fa-solid fa-cloud-sun', icon: faCloudSun },
  { cls: 'fa-solid fa-cloud-rain', icon: faCloudRain },
  { cls: 'fa-solid fa-snowflake', icon: faSnowflake },
  { cls: 'fa-solid fa-umbrella', icon: faUmbrella },
  { cls: 'fa-solid fa-wrench', icon: faWrench },
  { cls: 'fa-solid fa-tools', icon: faTools },
  { cls: 'fa-solid fa-toolbox', icon: faToolbox },
  { cls: 'fa-solid fa-screwdriver', icon: faScrewdriver },
  { cls: 'fa-solid fa-hammer', icon: faHammer },
  { cls: 'fa-solid fa-paintbrush', icon: faPaintbrush },
  { cls: 'fa-solid fa-palette', icon: faPalette },
  { cls: 'fa-solid fa-magic', icon: faMagic },
  { cls: 'fa-solid fa-wand-magic-sparkles', icon: faWandMagicSparkles },
  { cls: 'fa-solid fa-music', icon: faMusic },
  { cls: 'fa-solid fa-image', icon: faImage },
  { cls: 'fa-solid fa-video', icon: faVideo },
  { cls: 'fa-solid fa-camera', icon: faCamera },
  { cls: 'fa-solid fa-microphone', icon: faMicrophone },
  { cls: 'fa-solid fa-headphones', icon: faHeadphones },
  { cls: 'fa-solid fa-bell', icon: faBell },
  { cls: 'fa-solid fa-flag', icon: faFlag },
  { cls: 'fa-solid fa-bookmark', icon: faBookmark },
  { cls: 'fa-solid fa-tag', icon: faTag },
  { cls: 'fa-solid fa-tags', icon: faTags },
  { cls: 'fa-solid fa-store', icon: faStore },
  { cls: 'fa-solid fa-folder', icon: faFolder },
  { cls: 'fa-solid fa-folder-open', icon: faFolderOpen },
  { cls: 'fa-solid fa-folder-plus', icon: faFolderPlus },
  { cls: 'fa-solid fa-folder-minus', icon: faFolderMinus },
  { cls: 'fa-solid fa-file', icon: faFile },
  { cls: 'fa-solid fa-file-lines', icon: faFileLines },
  { cls: 'fa-solid fa-file-code', icon: faFileCode },
  { cls: 'fa-solid fa-layer-group', icon: faLayerGroup },
  { cls: 'fa-solid fa-project-diagram', icon: faProjectDiagram },
  { cls: 'fa-solid fa-sitemap', icon: faSitemap },
  { cls: 'fa-solid fa-chart-bar', icon: faChartBar },
  { cls: 'fa-solid fa-chart-line', icon: faChartLine },
  { cls: 'fa-solid fa-chart-pie', icon: faChartPie },
  { cls: 'fa-solid fa-calendar', icon: faCalendar },
  { cls: 'fa-solid fa-clock', icon: faClock },
  { cls: 'fa-solid fa-history', icon: faHistory },
  { cls: 'fa-solid fa-hourglass', icon: faHourglass },
  { cls: 'fa-solid fa-stopwatch', icon: faStopwatch },
  { cls: 'fa-solid fa-battery-full', icon: faBatteryFull },
  { cls: 'fa-solid fa-battery-half', icon: faBatteryHalf },
  { cls: 'fa-solid fa-battery-empty', icon: faBatteryEmpty },
  { cls: 'fa-solid fa-plug', icon: faPlug },
  { cls: 'fa-solid fa-power-off', icon: faPowerOff },
  { cls: 'fa-solid fa-toggle-on', icon: faToggleOn },
  { cls: 'fa-solid fa-toggle-off', icon: faToggleOff },
  { cls: 'fa-solid fa-square', icon: faSquare },
  { cls: 'fa-solid fa-square-check', icon: faSquareCheck },
  { cls: 'fa-solid fa-circle', icon: faCircle },
  { cls: 'fa-solid fa-circle-dot', icon: faCircleDot },
  { cls: 'fa-solid fa-filter', icon: faFilter },
  { cls: 'fa-solid fa-sort', icon: faSort },
  { cls: 'fa-solid fa-sort-up', icon: faSortUp },
  { cls: 'fa-solid fa-sort-down', icon: faSortDown },
  { cls: 'fa-solid fa-arrow-up', icon: faArrowUp },
  { cls: 'fa-solid fa-arrow-down', icon: faArrowDown },
  { cls: 'fa-solid fa-arrow-left', icon: faArrowLeft },
  { cls: 'fa-solid fa-arrow-right', icon: faArrowRight },
  { cls: 'fa-solid fa-chevron-up', icon: faChevronUp },
  { cls: 'fa-solid fa-chevron-down', icon: faChevronDown },
  { cls: 'fa-solid fa-chevron-left', icon: faChevronLeft },
  { cls: 'fa-solid fa-chevron-right', icon: faChevronRight },
  { cls: 'fa-solid fa-angle-up', icon: faAngleUp },
  { cls: 'fa-solid fa-angle-down', icon: faAngleDown },
  { cls: 'fa-solid fa-angle-left', icon: faAngleLeft },
  { cls: 'fa-solid fa-angle-right', icon: faAngleRight },
  { cls: 'fa-solid fa-up-right-and-down-left-from-center', icon: faUpRightAndDownLeftFromCenter },
  { cls: 'fa-solid fa-down-left-and-up-right-to-center', icon: faDownLeftAndUpRightToCenter },
  { cls: 'fa-solid fa-right-left', icon: faRightLeft },
  { cls: 'fa-solid fa-rotate-left', icon: faRotateLeft },
  { cls: 'fa-solid fa-rotate-right', icon: faRotateRight },
  { cls: 'fa-solid fa-clipboard', icon: faClipboard },
  { cls: 'fa-solid fa-clipboard-check', icon: faClipboardCheck },
  { cls: 'fa-solid fa-clipboard-list', icon: faClipboardList },
  { cls: 'fa-solid fa-list', icon: faList },
  { cls: 'fa-solid fa-list-ul', icon: faListUl },
  { cls: 'fa-solid fa-list-ol', icon: faListOl },
  { cls: 'fa-solid fa-list-check', icon: faListCheck },
  { cls: 'fa-solid fa-table', icon: faTable },
  { cls: 'fa-solid fa-table-cells', icon: faTableCells },
  { cls: 'fa-solid fa-table-list', icon: faTableList },
  { cls: 'fa-solid fa-table-columns', icon: faTableColumns },
  { cls: 'fa-solid fa-align-left', icon: faAlignLeft },
  { cls: 'fa-solid fa-align-center', icon: faAlignCenter },
  { cls: 'fa-solid fa-align-right', icon: faAlignRight },
  { cls: 'fa-solid fa-align-justify', icon: faAlignJustify },
  { cls: 'fa-solid fa-bold', icon: faBold },
  { cls: 'fa-solid fa-italic', icon: faItalic },
  { cls: 'fa-solid fa-underline', icon: faUnderline },
  { cls: 'fa-solid fa-strikethrough', icon: faStrikethrough },
  { cls: 'fa-solid fa-quote-left', icon: faQuoteLeft },
  { cls: 'fa-solid fa-quote-right', icon: faQuoteRight },
  { cls: 'fa-solid fa-eye', icon: faEye },
  { cls: 'fa-solid fa-eye-slash', icon: faEyeSlash },
  { cls: 'fa-solid fa-expand', icon: faExpand },
  { cls: 'fa-solid fa-compress', icon: faCompress },
  { cls: 'fa-solid fa-volume-up', icon: faVolumeUp },
  { cls: 'fa-solid fa-volume-down', icon: faVolumeDown },
  { cls: 'fa-solid fa-volume-mute', icon: faVolumeMute },
  { cls: 'fa-solid fa-backward', icon: faBackward },
  { cls: 'fa-solid fa-forward', icon: faForward },
  { cls: 'fa-solid fa-step-backward', icon: faStepBackward },
  { cls: 'fa-solid fa-step-forward', icon: faStepForward },
  { cls: 'fa-solid fa-long-arrow-up', icon: faLongArrowUp },
  { cls: 'fa-solid fa-long-arrow-down', icon: faLongArrowDown },
  { cls: 'fa-solid fa-long-arrow-alt-left', icon: faLongArrowAltLeft },
  { cls: 'fa-solid fa-long-arrow-alt-right', icon: faLongArrowAltRight },
  // brands
  { cls: 'fa-brands fa-github', icon: faGithub },
  { cls: 'fa-brands fa-gitlab', icon: faGitlab },
  { cls: 'fa-brands fa-bitbucket', icon: faBitbucket },
  { cls: 'fa-brands fa-discord', icon: faDiscord },
  { cls: 'fa-brands fa-telegram', icon: faTelegram },
  { cls: 'fa-brands fa-twitter', icon: faTwitter },
  { cls: 'fa-brands fa-x-twitter', icon: faXTwitter },
  { cls: 'fa-brands fa-youtube', icon: faYoutube },
  { cls: 'fa-brands fa-twitch', icon: faTwitch },
  { cls: 'fa-brands fa-reddit', icon: faReddit },
  { cls: 'fa-brands fa-steam', icon: faSteam },
  { cls: 'fa-brands fa-xbox', icon: faXbox },
  { cls: 'fa-brands fa-playstation', icon: faPlaystation },
  { cls: 'fa-brands fa-linux', icon: faLinux },
  { cls: 'fa-brands fa-windows', icon: faWindows },
  { cls: 'fa-brands fa-apple', icon: faApple },
  { cls: 'fa-brands fa-android', icon: faAndroid },
  { cls: 'fa-brands fa-chrome', icon: faChrome },
  { cls: 'fa-brands fa-firefox', icon: faFirefox },
  { cls: 'fa-brands fa-safari', icon: faSafari },
  { cls: 'fa-brands fa-edge', icon: faEdge },
  { cls: 'fa-brands fa-python', icon: faPython },
  { cls: 'fa-brands fa-js', icon: faJs },
  { cls: 'fa-brands fa-html5', icon: faHtml5 },
  { cls: 'fa-brands fa-css3-alt', icon: faCss3Alt },
  { cls: 'fa-brands fa-react', icon: faReact },
  { cls: 'fa-brands fa-vuejs', icon: faVuejs },
  { cls: 'fa-brands fa-angular', icon: faAngular },
  { cls: 'fa-brands fa-node-js', icon: faNodeJs },
  { cls: 'fa-brands fa-git', icon: faGit },
  { cls: 'fa-brands fa-git-alt', icon: faGitAlt },
  { cls: 'fa-brands fa-docker', icon: faDocker },
  { cls: 'fa-brands fa-aws', icon: faAws },
  { cls: 'fa-brands fa-microsoft', icon: faMicrosoft },
  { cls: 'fa-brands fa-java', icon: faJava },
  { cls: 'fa-brands fa-php', icon: faPhp },
  { cls: 'fa-brands fa-rust', icon: faRust },
  { cls: 'fa-brands fa-swift', icon: faSwift },
  { cls: 'fa-brands fa-cc-visa', icon: faCcVisa },
  { cls: 'fa-brands fa-cc-mastercard', icon: faCcMastercard },
  { cls: 'fa-brands fa-cc-paypal', icon: faCcPaypal },
  { cls: 'fa-brands fa-cc-stripe', icon: faCcStripe },
  { cls: 'fa-brands fa-cc-amex', icon: faCcAmex },
  { cls: 'fa-brands fa-bitcoin', icon: faBitcoin },
  { cls: 'fa-brands fa-ethereum', icon: faEthereum },
  { cls: 'fa-brands fa-tiktok', icon: faTiktok },
  { cls: 'fa-brands fa-instagram', icon: faInstagram },
  { cls: 'fa-brands fa-facebook', icon: faFacebook },
  { cls: 'fa-brands fa-weixin', icon: faWeixin },
  { cls: 'fa-brands fa-qq', icon: faQq },
  { cls: 'fa-brands fa-zhihu', icon: faZhihu },
  { cls: 'fa-brands fa-ubuntu', icon: faUbuntu },
  { cls: 'fa-brands fa-debian', icon: faDebian },
  { cls: 'fa-brands fa-archlinux', icon: faArchLinux },
]

const byClass = new Map(entries.map(e => [e.cls, e.icon]))

export function BuiltinFaIcon({ cls, className }: { cls: string; className?: string }) {
  const icon = byClass.get(cls)
  if (!icon) return null
  return <FontAwesomeIcon icon={icon} className={className} />
}

export function resolveFaIcon(icon: string): IconDefinition | undefined {
  if (!icon.startsWith('fa-')) return undefined
  return byClass.get(icon)
}
